### ISSUE TITLE
binary mixture

### ISSUE THREAD

**Issue by achremos** [Santiso-Group/despasito#31]
Bubble + dew point routines use the composition as input and estimate the pressure. But this needs to be expanded.

What is missing (I think) is a routine that uses the xi or yi as initial guesses and provides resulting values of the xi and yi at specified conditions of T and P.

**Comment by jaclark5** [comment]
You'll find that there is already a flash calculation type, although as a warning this type of thermodynamic calculation is notoriously unstable to converge.

**Comment by achremos** [comment]
Will initial guesses for compositions improve the stability & convergence of the calculation by searching at regions of interest? 

In SW bubble point requires an initial guess.

**Comment by jaclark5** [comment]
Yes it will! Make sure you're using a gradient decent optimization method in that case so that the initial guess is used. You can also apply a tighter pressure range to search.
