### ISSUE TITLE
[General] Add contributing guidelines

### ISSUE THREAD

**Issue by JacksonBurns** [Santiso-Group/despasito#37]
**Describe the issue**
The README welcomes contributions, but some more explicit directions can be helpful to new users.

**Expected behavior**
Consider the official GitHub guidelines for writing these guidelines: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

**Additional context**
This issue is part of an ongoing JOSS review at https://github.com/openjournals/joss-reviews/issues/7365

**Comment by JacksonBurns** [comment]
I see actually that you have some guidelines here: https://github.com/Santiso-Group/despasito/tree/master/devtools#how-to-contribute-changes

Maybe just link to this document in the README, and expand it?

**Comment by jaclark5** [comment]
@JacksonBurns this was addressed in #39, let me know what you think! Sorry I accidentally committed these changes to another PR.

**Comment by jaclark5** [comment]
Changed for these comments have been moved to #40

**Comment by JacksonBurns** [comment]
I left a small comment about a typo but it looks good to me otherwise!

**Comment by JacksonBurns** [comment]
Feel free to close after merging that PR
